# Generated by Django 5.0.2 on 2024-02-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegModel',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Enter full Name', max_length=100, null=True)),
                ('email', models.EmailField(help_text='Enter Email Address', max_length=100, null=True)),
                ('phone_number', models.BigIntegerField()),
                ('photo', models.ImageField(default='image', null=True, upload_to='images/')),
                ('password', models.CharField(help_text='Enter Password', max_length=10, null=True)),
                ('reg_date', models.DateField(auto_now_add=True, null=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Student_Details',
            },
        ),
    ]
