# Generated by Django 5.0.2 on 2024-02-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregmodel',
            name='otp',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='studentregmodel',
            name='otp_status',
            field=models.CharField(default='Not Verified', max_length=15),
        ),
    ]
