# Generated by Django 5.0.2 on 2024-02-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_studentcourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourses',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourses',
            name='student',
        ),
        migrations.DeleteModel(
            name='CartModel',
        ),
        migrations.DeleteModel(
            name='StudentCourses',
        ),
    ]
