# Generated by Django 5.0.2 on 2024-02-23 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_cartmodel_studentcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('test_id', models.IntegerField(null=True)),
                ('test_name', models.CharField(max_length=155)),
                ('question', models.CharField(max_length=155)),
                ('useranswer', models.CharField(max_length=55)),
                ('correctanswer', models.CharField(max_length=55)),
                ('marks', models.IntegerField()),
                ('result_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Student_Result_Details',
            },
        ),
        migrations.CreateModel(
            name='UserTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=155, unique=True)),
                ('test_date', models.DateField(auto_now_add=True)),
                ('test_marks', models.IntegerField(default=0)),
                ('test_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='userapp.studentregmodel')),
            ],
            options={
                'db_table': 'User_tests_details',
            },
        ),
    ]
