# Generated by Django 4.1.3 on 2024-03-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_studentfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourses',
            name='payment_id',
        ),
    ]
