# Generated by Django 5.0.6 on 2024-07-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0011_remove_studentcourses_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourses",
            name="certificate_downloaded",
            field=models.BooleanField(default=False),
        ),
    ]
