# Generated by Django 5.0.2 on 2024-02-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorRegModel',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=55)),
                ('email', models.EmailField(help_text='Enter Email', max_length=100)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('gender', models.CharField(default=False, max_length=50)),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
                ('photo', models.ImageField(default=False, upload_to='')),
                ('status', models.CharField(default='Pending', max_length=100, null=True)),
                ('reg_date', models.DateField(auto_now_add=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('otp', models.CharField(default=0, max_length=6)),
                ('otp_status', models.CharField(default='Not Verified', max_length=15)),
            ],
            options={
                'db_table': 'Instructor_Details',
            },
        ),
    ]
