# Generated by Django 5.0.2 on 2024-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0002_addourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='addourse',
            name='added_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
