# Generated by Django 5.0.2 on 2024-02-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0003_addourse_added_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addourse',
            new_name='Addcourse',
        ),
    ]
