# Generated by Django 5.0.2 on 2024-02-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0005_question'),
        ('userapp', '0007_remove_studentcourses_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Addcourse',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
