# Generated by Django 5.0.2 on 2024-02-23 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0006_remove_question_course_remove_question_instructor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addcourse',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_image', models.ImageField(upload_to='course_images/')),
                ('course_category', models.CharField(max_length=100)),
                ('course_language', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('video_url', models.URLField()),
                ('duration_weeks', models.IntegerField()),
                ('price', models.CharField(max_length=10)),
                ('added_date', models.DateField(auto_now_add=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructorapp.instructorregmodel')),
            ],
            options={
                'db_table': 'Courses_details',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructorapp.addcourse')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructorapp.instructorregmodel')),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
    ]
