# Generated by Django 3.2 on 2025-03-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0009_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_name', models.CharField(max_length=255)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
